{{- range .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default $.Values.name .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "specific.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .data }}
data:
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- with .binaryData }}
binaryData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
