{{- if .Values.HorizontalPodAutoscaler.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.name }}
  minReplicas: {{ .Values.HorizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.HorizontalPodAutoscaler.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.HorizontalPodAutoscaler.averageUtilization }}
{{- end }}
