{{- if .Values.pvc.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "specific.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  {{- if .Values.pvc.storageClass }}
    {{- if eq "-" .Values.pvc.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.pvc.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
