---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "specific.labels" . | nindent 4 }}
spec:
  endpoints:
    {{- range .Values.servicemonitor.endpoints }}
    - interval: {{ .interval }}
      path: {{ .path }}
      port: {{ .port }}
      scheme: {{ .scheme }}
    {{- end }}
  selector:
    matchExpressions:
      - key: prometheus.io/service-monitor
        operator: NotIn
        values:
          - 'false'
    matchLabels:
      {{- include "specific.labels" . | nindent 6 }}
